name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      GH_TOKEN_REPO:
        description: "PAT"
      LANDO_ENV:
        description: ".env variables"
      CREATEUSERS:
        description: "Dev users script"
      SERVICENOW_KEY:
        description: "Servicenow key"
      ENCRYPT_KEY:
        description: "One key to rule them all"
      TEAMS_KEY:
        description: "Key to send teams messages"
      LIASON:
        description: "Liason Key"
      SUBSCRIPTIONS_KEY:
        description: "Subscriptions key"
      DATABASE:
        description: "Use specific backup"
      CONFIG_SYNC:
        description: "Run config sync boolean"
      SITE:
        description: "Site to test"
permissions:
  actions: read
  contents: write
jobs:
  behat:
    name: Cypress tests
    runs-on: ubuntu-latest
    environment: oit-ci
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Extract branch name
        id: extract_branch
        run: |
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            branch_name=${GITHUB_REF#refs/heads/}
          elif [[ $GITHUB_HEAD_REF != "" ]]; then
            branch_name=$GITHUB_HEAD_REF
          else
            branch_name="md-dev"  # Default to md-dev if we can't determine branch
          fi
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "Branch name: $branch_name"

      - name: ddev
        uses: UCBoulder/oitid_ddev_start@2.0
        env:
          site: ${{ secrets.SITE }}
        if: env.BRANCH_NAME == 'md-dev' || (env.site == 'oit' || env.site == 'data' || env.site == 'data1')
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.GH_TOKEN_REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANDO_ENV: ${{ secrets.LANDO_ENV }}
          CREATEUSERS: ${{ secrets.CREATEUSERS }}
          SERVICENOW_KEY: ${{ secrets.SERVICENOW_KEY }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          TEAMS_KEY: ${{ secrets.TEAMS_KEY }}
          LIASON: ${{ secrets.LIASON }}
          SUBSCRIPTIONS_KEY: ${{ secrets.SUBSCRIPTIONS_KEY }}
          CONFIG_SYNC: 1

      - name: Run Cypress tests
        env:
          site: ${{ secrets.SITE }}
        if: env.BRANCH_NAME == 'md-dev' || (env.site == 'oit' || env.site == 'data' || env.site == 'data1')
        run: |
          domain=$(echo "$SITE" | sed 's/[0-9]//g')
          vendor/bin/robo cypress $site

      - name: Screenshots artifact
        if: failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: cypress-screenshots-${{ secrets.SITE }}
          path: tests/cypress/cypress/screenshots
          retention-days: 1
