name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      GH_TOKEN_REPO:
        description: "PAT"
      LANDO_ENV:
        description: ".env variables"
      CREATEUSERS:
        description: "Dev users script"
      SERVICENOW_KEY:
        description: "Servicenow key"
      ENCRYPT_KEY:
        description: "One key to rule them all"
      TEAMS_KEY:
        description: "Key to send teams messages"
      LIASON:
        description: "Liason Key"
      SUBSCRIPTIONS_KEY:
        description: "Subscriptions key"
      DATABASE:
        description: "Use specific backup"
      CONFIG_SYNC:
        description: "Run config sync boolean"
      SITE:
        description: "Site to test"
permissions:
  actions: read
  contents: write
jobs:
  behat:
    name: Cypress tests
    runs-on: ubuntu-latest
    environment: oit-ci
    steps:
      - uses: actions/checkout@v4.1.1

      - id: Lando
        uses: UCBoulder/oitid_lando_start@v2.7
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.GH_TOKEN_REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANDO_ENV: ${{ secrets.LANDO_ENV }}
          CREATEUSERS: ${{ secrets.CREATEUSERS }}
          SERVICENOW_KEY: ${{ secrets.SERVICENOW_KEY }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          TEAMS_KEY: ${{ secrets.TEAMS_KEY }}
          LIASON: ${{ secrets.LIASON }}
          SUBSCRIPTIONS_KEY: ${{ secrets.SUBSCRIPTIONS_KEY }}
          CONFIG_SYNC: 1

      - name: Run Cypress tests
        run: |
          lando curl
          cd tests/cypress
          domain=$(echo "$SITE" | sed 's/[0-9]//g')
          lando cypress run --config baseUrl=https://$domain.lndo.site/ -s cypress/e2e/$SITE
        env:
          SITE: ${{ secrets.SITE }}

      - name: Screenshots artifact
        if: failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: screenshots
          path: tests/cypress/cypress/${{ secrets.SITE }}
          retention-days: 1
