name: (M) Cypress Tests
on:
  workflow_call:
    secrets:
      GH_TOKEN_REPO:
        description: "PAT"
      LANDO_ENV:
        description: ".env variables"
      DATABASE:
        description: "Use specific backup"
      CONFIG_SYNC:
        description: "Run config sync boolean"
      SITE:
        description: "Site to test"
      PANTHEON_SECRETS:
        description: "Pantheon secrets file"
permissions:
  actions: read
  contents: write
jobs:
  cypress:
    name: Cypress tests
    runs-on: ubuntu-latest
    environment: oit-ci
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Extract branch name
        id: extract_branch
        run: |
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            branch_name=${GITHUB_REF#refs/heads/}
          elif [[ $GITHUB_HEAD_REF != "" ]]; then
            branch_name=$GITHUB_HEAD_REF
          else
            branch_name="md-dev"  # Default to md-dev if we can't determine branch
          fi
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "Branch name: $branch_name"

      - name: Set panthon secrets
        run: |
          touch secrets.json
          echo "$PANTHEON_SECRETS" > secrets.json
        env:
          PANTHEON_SECRETS: ${{ secrets.PANTHEON_SECRETS }}

      - name: ddev
        uses: UCBoulder/oitid_ddev_start@v2.4
        env:
          site: ${{ secrets.SITE }}
        if: env.BRANCH_NAME == 'md-dev' || (env.site == 'oit' || env.site == 'oit1'|| env.site == 'data' || env.site == 'data1')
        with:
          DATABASE: ${{ secrets.DATABASE }}
          GH_TOKEN_REPO: ${{ secrets.GH_TOKEN_REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANDO_ENV: ${{ secrets.LANDO_ENV }}
          CONFIG_SYNC: 1

      - name: Run Cypress tests
        env:
          site: ${{ secrets.SITE }}
        if: env.BRANCH_NAME == 'md-dev' || (env.site == 'oit' || env.site == 'data' || env.site == 'data1')
        run: |
          domain=$(echo "$SITE" | sed 's/[0-9]//g')
          vendor/bin/robo cypress $site

      - name: Screenshots artifact
        if: failure()
        uses: actions/upload-artifact@v7.0.0
        with:
          name: cypress-screenshots-${{ secrets.SITE }}
          path: tests/cypress/cypress/screenshots
          retention-days: 1
