name: (A) PHPCS
on:
  push:
    branches:
      - '*'
  workflow_call:
    secrets:
      phpstan_level:
        required: false
        description: ''
jobs:
  deploy:
    name: Run phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: UCBoulder/oitid_reusable_actions/.github/actions/cs
