name: (A) PHPCS
on:
  push:
    branches:
      - '*'
  workflow_call:
jobs:
  deploy:
    name: Run phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/cs
