name: (A) PHPCS
on:
  push:
    branches:
      - '*'
  workflow_call:
    secrets:
      phpstan_level:
        required: false
        description: ''
jobs:
  deploy:
    name: Run phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: drupal_repo
      - name: Checkout workflows repo # required so we can reference the actions locally
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.workflows-ref }}
          path: workflows
          repository: UCBoulder/oitid_reusable_actions
      - uses: ./workflows/.github/actions/cs
