name: (A) PHPCS
on:
  push:
    branches:
      - '*'
  workflow_call:
    secrets:
      phpstan_level:
        required: false
        description: ''
jobs:
  deploy:
    name: Run phpcs
    runs-on: protitude/oit-actions
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          export PATH="$PATH:/root/drupal/vendor/bin"
          echo "--------- CS O'Clock -------------"
          phpcs --standard=Drupal,DrupalPractice ./

          if [ -n "${phpstan_level+set}" ]; then
            echo "Running phpstan at level $phpstan_level"
            phpstan analyse -l $phpstan_level ./
          fi
