name: (M) Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag next major/minor release. Use 1.x.x scheme. Leave default iterate to auto tag the next patch version.'
        required: true
        default: 'iterate'
  workflow_call:
    inputs:
      version:
        description: 'Tag next major/minor release. Use 1.x.x scheme. Leave default iterate to auto tag the next patch version.'
        required: false
        default: 'iterate'
        type: string
permissions:
  contents: write
jobs:
  release:
    name: Tag code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Create/push tag
        run: |
          git remote set-url origin https://$gh_user:$gh_token@github.com/$repo.git
          git config --global user.email "buffalor@colorado.edu"
          git config --global user.name "$gh_user"
          git fetch origin
          latest_sha=$(git rev-list --tags --max-count=1)
          current_version=$(git describe --tags --abbrev=0)
          current_branch=${GITHUB_REF##*/}
          if [[ "${set_version}" == 'iterate' ]]
          then
            next_version=$(echo "${current_version}" | awk -F. -v OFS=. '{$NF += 1 ; print}')
            next_version_message="Patch level change, see release notes for more info"
          else
            next_version="${set_version}"
            next_version_message="New major/minor release, see release notes for more info"
          fi
          git tag -a "$next_version" -m "$next_version_message"
          git push origin --tags
          echo '# CHANGELOG' > release.md
          git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s' "${latest_sha}..${current_branch}" --no-merges >> release.md
          gh release create "$next_version" \
            --title "$next_version" \
            --notes-file release.md
        env:
          set_version: ${{ inputs.version || 'iterate' }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_user: ${{ github.actor }}
          repo: ${{ github.repository }}
