name: (A) Module Testing
on:
  workflow_call:
    secrets:
      ralphie_token:
        required: true
        description: 'Token to be used as GH_TOKEN'
      repo:
        required: true
        description: 'The repository name'
      branch:
        required: true
        description: 'The repository branch'
      phpstan_level:
        required: false
        description: ''
jobs:
  deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Get Repo Name
        run: echo "BRANCH=$(echo $branch | awk -F / '{print $3}')" >> $GITHUB_ENV
        env:
          branch: ${{ secrets.branch }}
      - name: Trigger Tests
        run: |
          echo "Testing $REPO on branch $BRANCH"
          gh workflow run codetesting.yml -f modules="['$REPO']" -f phpstan_level=$level -f branch=$BRANCH -R UCBoulder/oit_dingo
        env:
          level: ${{ secrets.phpstan_level }}
          GH_TOKEN: ${{ secrets.ralphie_token }}
          REPO: ${{ secrets.repo }}
