name: (A) Module Testing
on:
  workflow_call:
    secrets:
      ralphie_token:
        required: true
        description: 'Token to be used as GH_TOKEN'
      phpstan_level:
        required: false
        description: ''
jobs:
  deploy:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Get Repo Name
        run: echo "BRANCH=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV
      - name: Trigger Tests
        run: |
          touch test.txt
          echo "Branch: $BRANCH - Repo: $REPO" >> test.txt
          echo "Testing $REPO on branch $BRANCH"
          gh workflow run codetesting.yml -f modules="['$REPO']" -f phpstan_level=$level -f branch=$BRANCH -R UCBoulder/oit_dingo
        env:
          level: ${{ secrets.phpstan_level }}
          GH_TOKEN: ${{ secrets.ralphie_token }}
          REPO: ${{ github.event.repository.name }}

      - name: 'Testing artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Test
          path: test.txt
          retention-days: 1

